-- MySQL Script generated by MySQL Workbench
-- Wed Apr  3 16:17:18 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`countries` (
  `idcountries` SMALLINT NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcountries`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`states`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`states` (
  `idstates` SMALLINT NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `countries_idcountries` SMALLINT NOT NULL,
  PRIMARY KEY (`idstates`, `countries_idcountries`),
  INDEX `fk_states_countries1_idx` (`countries_idcountries` ASC) VISIBLE,
  CONSTRAINT `fk_states_countries1`
    FOREIGN KEY (`countries_idcountries`)
    REFERENCES `mydb`.`countries` (`idcountries`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cities` (
  `idcities` SMALLINT NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `states_idstates` SMALLINT NOT NULL,
  PRIMARY KEY (`idcities`, `states_idstates`),
  INDEX `fk_cities_states1_idx` (`states_idstates` ASC) VISIBLE,
  CONSTRAINT `fk_cities_states1`
    FOREIGN KEY (`states_idstates`)
    REFERENCES `mydb`.`states` (`idstates`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Addresses` (
  `idAddresses` SMALLINT NOT NULL,
  `postalcode` INT(7) NOT NULL,
  `region` VARCHAR(45) NOT NULL,
  `market` VARCHAR(15) NOT NULL,
  `cities_idcities` SMALLINT NOT NULL,
  PRIMARY KEY (`idAddresses`, `cities_idcities`),
  INDEX `fk_Addresses_cities1_idx` (`cities_idcities` ASC) VISIBLE,
  CONSTRAINT `fk_Addresses_cities1`
    FOREIGN KEY (`cities_idcities`)
    REFERENCES `mydb`.`cities` (`idcities`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customers` (
  `idcustomer` SMALLINT NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `segment` VARCHAR(45) NOT NULL,
  `Addresses_idAddresses` SMALLINT NOT NULL,
  PRIMARY KEY (`idcustomer`, `Addresses_idAddresses`),
  INDEX `fk_customers_Addresses1_idx` (`Addresses_idAddresses` ASC) VISIBLE,
  CONSTRAINT `fk_customers_Addresses1`
    FOREIGN KEY (`Addresses_idAddresses`)
    REFERENCES `mydb`.`Addresses` (`idAddresses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`products` (
  `idproduct` SMALLINT NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `subcategory` VARCHAR(45) NOT NULL,
  `productname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idproduct`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ship` (
  `idship` SMALLINT NOT NULL,
  `shipdate` DATETIME NOT NULL,
  `shipmode` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idship`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orders` (
  `idorder` SMALLINT NOT NULL,
  `orderdate` DATETIME NULL,
  `orderpriority` VARCHAR(45) NOT NULL,
  `customers_idcustomer` SMALLINT NOT NULL,
  `products_idproduct` SMALLINT NOT NULL,
  `ship_idship` SMALLINT NOT NULL,
  PRIMARY KEY (`idorder`, `customers_idcustomer`, `products_idproduct`, `ship_idship`),
  INDEX `fk_orders_customers_idx` (`customers_idcustomer` ASC) VISIBLE,
  INDEX `fk_orders_products1_idx` (`products_idproduct` ASC) VISIBLE,
  INDEX `fk_orders_ship1_idx` (`ship_idship` ASC) VISIBLE,
  CONSTRAINT `fk_orders_customers`
    FOREIGN KEY (`customers_idcustomer`)
    REFERENCES `mydb`.`customers` (`idcustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_products1`
    FOREIGN KEY (`products_idproduct`)
    REFERENCES `mydb`.`products` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_ship1`
    FOREIGN KEY (`ship_idship`)
    REFERENCES `mydb`.`ship` (`idship`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sales` (
  `idsales` SMALLINT NOT NULL,
  `sales` DECIMAL NOT NULL,
  `quantity` INT NOT NULL,
  `discount` DECIMAL NOT NULL,
  `profit` DECIMAL(2) NOT NULL,
  `shippingcost` DECIMAL NOT NULL,
  `products_idproduct` SMALLINT NOT NULL,
  PRIMARY KEY (`idsales`, `products_idproduct`),
  INDEX `fk_sales_products1_idx` (`products_idproduct` ASC) VISIBLE,
  CONSTRAINT `fk_sales_products1`
    FOREIGN KEY (`products_idproduct`)
    REFERENCES `mydb`.`products` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
